#!/bin/sh
echo "Removing existing files"
rm -rf web/public/*

echo "Generating site"

cd web

hugo

cd ..

echo "Updating gh-pages branch"

git add dist && git commit -m "Publishing to gh-pages"

git subtree push --prefix web/public origin gh-pages