#!/bin/sh

if [ "`git status -s`" ]
then
    echo "The working directory is dirty. Please commit any pending changes."
    exit 1;
fi

echo "Deleting old web/publication"
rm -rf web/public
mkdir web/public
git worktree prune
rm -rf ../.git/worktrees/web/public/

echo "Checking out gh-pages branch into web/public"
git worktree add -B gh-pages web/public upstream/gh-pages

echo "Removing existing files"
rm -rf web/public/*

echo "Generating site"
hugo

echo "Updating gh-pages branch"
cd web/public && git add --all && git commit -m "Publishing to gh-pages (publish.sh)"

#echo "Pushing to github"
git push --all